export type FirearmCategory =
  | 'pistol'
  | 'rifle'
  | 'shotgun'
  | 'sniper'
  | 'machine'
  | 'revolver';

export interface Firearm {
  id: string;
  name: string;
  category: FirearmCategory;
  description: string;
  caliber: string;
  barrelLength: string;
  weight: string;
  magazineCapacity: number;
  muzzleVelocity: string;
  origin: string;
  manufacturer: string;
  year: number;
  specs: {
    type: string;
    action: string;
    safeties: string;
    sight: string;
  };
  color: string;
}

export interface CategoryDefinition {
  id: FirearmCategory;
  name: string;
  icon: string;
  description: string;
  color: string;
}

export interface CategorySummary extends CategoryDefinition {
  count: number;
}

export interface StatSummary {
  label: string;
  value: string | number;
  icon: string;
}

export const categoryDefinitions: CategoryDefinition[] = [
  {
    id: 'pistol',
    name: 'Pistols',
    icon: 'Pistol',
    description: 'Sidearms and service pistols',
    color: 'from-slate-600 to-stone-500',
  },
  {
    id: 'rifle',
    name: 'Rifles',
    icon: 'Rifle',
    description: 'Service and sporting rifles',
    color: 'from-amber-700 to-amber-500',
  },
  {
    id: 'shotgun',
    name: 'Shotguns',
    icon: 'Shotgun',
    description: 'Pump and semi-auto shotguns',
    color: 'from-emerald-700 to-emerald-500',
  },
  {
    id: 'sniper',
    name: 'Precision Rifles',
    icon: 'Scope',
    description: 'Long-range precision platforms',
    color: 'from-indigo-700 to-violet-500',
  },
  {
    id: 'machine',
    name: 'Automatic Arms',
    icon: 'Zap',
    description: 'Machine guns, SMGs, and PDWs',
    color: 'from-rose-700 to-orange-500',
  },
  {
    id: 'revolver',
    name: 'Revolvers',
    icon: 'RotateCcw',
    description: 'Classic revolving handguns',
    color: 'from-zinc-700 to-stone-500',
  },
];

export const firearmsFallback: Firearm[] = [
  {
    id: 'glock-17',
    name: 'Glock 17',
    category: 'pistol',
    description: 'Full-size polymer service pistol adopted widely by police and military units.',
    caliber: '9x19mm Parabellum',
    barrelLength: '4.49 in',
    weight: '25.1 oz',
    magazineCapacity: 17,
    muzzleVelocity: 'About 1,150 ft/s',
    origin: 'Austria',
    manufacturer: 'Glock',
    year: 1982,
    specs: {
      type: 'Semi-automatic striker-fired pistol',
      action: 'Short recoil, locked breech',
      safeties: 'Trigger, firing pin, and drop safeties',
      sight: 'Fixed low-profile sights',
    },
    color: 'from-slate-600 to-stone-500',
  },
  {
    id: 'glock-19',
    name: 'Glock 19',
    category: 'pistol',
    description: 'Compact version of the Glock platform with broad civilian and duty use.',
    caliber: '9x19mm Parabellum',
    barrelLength: '4.02 in',
    weight: '23.6 oz',
    magazineCapacity: 15,
    muzzleVelocity: 'About 1,150 ft/s',
    origin: 'Austria',
    manufacturer: 'Glock',
    year: 1988,
    specs: {
      type: 'Semi-automatic striker-fired pistol',
      action: 'Short recoil, locked breech',
      safeties: 'Trigger, firing pin, and drop safeties',
      sight: 'Fixed low-profile sights',
    },
    color: 'from-slate-600 to-stone-500',
  },
  {
    id: 'sig-sauer-p226',
    name: 'SIG Sauer P226',
    category: 'pistol',
    description: 'Military and law-enforcement sidearm known for reliability and accuracy.',
    caliber: '9x19mm Parabellum',
    barrelLength: '4.4 in',
    weight: '34 oz',
    magazineCapacity: 15,
    muzzleVelocity: 'About 1,150 ft/s',
    origin: 'Switzerland',
    manufacturer: 'SIG Sauer',
    year: 1984,
    specs: {
      type: 'Semi-automatic DA/SA pistol',
      action: 'Short recoil, locked breech',
      safeties: 'Decocking lever and firing pin safety',
      sight: 'Three-dot combat sights',
    },
    color: 'from-amber-700 to-stone-500',
  },
  {
    id: 'beretta-92fs',
    name: 'Beretta 92FS',
    category: 'pistol',
    description: 'Widely recognized service pistol and the civilian variant of the M9 family.',
    caliber: '9x19mm Parabellum',
    barrelLength: '4.9 in',
    weight: '33.3 oz',
    magazineCapacity: 15,
    muzzleVelocity: 'About 1,180 ft/s',
    origin: 'Italy',
    manufacturer: 'Beretta',
    year: 1975,
    specs: {
      type: 'Semi-automatic DA/SA pistol',
      action: 'Short recoil, falling locking block',
      safeties: 'Slide-mounted safety and decocker',
      sight: 'Three-dot sight',
    },
    color: 'from-stone-600 to-zinc-500',
  },
  {
    id: 'colt-m1911a1',
    name: 'Colt M1911A1',
    category: 'pistol',
    description: 'Classic .45 caliber sidearm that shaped American handgun design.',
    caliber: '.45 ACP',
    barrelLength: '5 in',
    weight: '39 oz',
    magazineCapacity: 7,
    muzzleVelocity: 'About 830 ft/s',
    origin: 'United States',
    manufacturer: 'Colt',
    year: 1911,
    specs: {
      type: 'Semi-automatic single-action pistol',
      action: 'Short recoil, tilting barrel',
      safeties: 'Thumb safety, grip safety, half-cock notch',
      sight: 'Fixed blade and notch sights',
    },
    color: 'from-amber-800 to-stone-600',
  },
  {
    id: 'cz-75',
    name: 'CZ 75',
    category: 'pistol',
    description: 'Steel-frame service pistol respected for ergonomics and smooth trigger feel.',
    caliber: '9x19mm Parabellum',
    barrelLength: '4.72 in',
    weight: '35.2 oz',
    magazineCapacity: 15,
    muzzleVelocity: 'About 1,150 ft/s',
    origin: 'Czechoslovakia',
    manufacturer: 'Ceska zbrojovka',
    year: 1975,
    specs: {
      type: 'Semi-automatic DA/SA pistol',
      action: 'Short recoil, locked breech',
      safeties: 'Manual safety and firing pin block',
      sight: 'Three-dot or adjustable sight',
    },
    color: 'from-slate-700 to-stone-500',
  },
  {
    id: 'hk-usp',
    name: 'HK USP',
    category: 'pistol',
    description: 'Modular German service pistol designed around durability and suppressor use.',
    caliber: '.45 ACP',
    barrelLength: '4.41 in',
    weight: '30.3 oz',
    magazineCapacity: 12,
    muzzleVelocity: 'About 850 ft/s',
    origin: 'Germany',
    manufacturer: 'Heckler & Koch',
    year: 1993,
    specs: {
      type: 'Semi-automatic DA/SA pistol',
      action: 'Short recoil, locked breech',
      safeties: 'Ambidextrous safety/decocker variants',
      sight: 'Fixed combat sights',
    },
    color: 'from-zinc-700 to-slate-500',
  },
  {
    id: 'walther-p99',
    name: 'Walther P99',
    category: 'pistol',
    description: 'Modern polymer pistol noted for its ergonomic grip and interchangeable backstraps.',
    caliber: '9x19mm Parabellum',
    barrelLength: '4 in',
    weight: '21 oz',
    magazineCapacity: 15,
    muzzleVelocity: 'About 1,200 ft/s',
    origin: 'Germany',
    manufacturer: 'Carl Walther GmbH',
    year: 1997,
    specs: {
      type: 'Semi-automatic striker-fired pistol',
      action: 'Short recoil, locked breech',
      safeties: 'Trigger and firing pin safeties',
      sight: 'Low-profile combat sights',
    },
    color: 'from-stone-600 to-zinc-500',
  },
  {
    id: 'smith-wesson-mp9',
    name: 'Smith & Wesson M&P9',
    category: 'pistol',
    description: 'Modern duty pistol built around a polymer frame and duty-grade reliability.',
    caliber: '9x19mm Parabellum',
    barrelLength: '4.25 in',
    weight: '24.7 oz',
    magazineCapacity: 17,
    muzzleVelocity: 'About 1,150 ft/s',
    origin: 'United States',
    manufacturer: 'Smith & Wesson',
    year: 2005,
    specs: {
      type: 'Semi-automatic striker-fired pistol',
      action: 'Short recoil, locked breech',
      safeties: 'Trigger safety and internal safeties',
      sight: 'Three-dot tactical sights',
    },
    color: 'from-amber-700 to-stone-500',
  },
  {
    id: 'ruger-sr9',
    name: 'Ruger SR9',
    category: 'pistol',
    description: 'Slim polymer pistol designed for carry and service use.',
    caliber: '9x19mm Parabellum',
    barrelLength: '4.14 in',
    weight: '26.5 oz',
    magazineCapacity: 17,
    muzzleVelocity: 'About 1,200 ft/s',
    origin: 'United States',
    manufacturer: 'Sturm, Ruger & Co.',
    year: 2007,
    specs: {
      type: 'Semi-automatic striker-fired pistol',
      action: 'Short recoil, locked breech',
      safeties: 'Manual thumb safety and trigger safety',
      sight: 'Fixed low-profile sights',
    },
    color: 'from-slate-700 to-stone-500',
  },
  {
    id: 'ar-15',
    name: 'AR-15',
    category: 'rifle',
    description: 'Modular civilian rifle platform that became a defining American design.',
    caliber: '5.56x45mm NATO',
    barrelLength: '16 in',
    weight: '6.5 to 7.5 lbs',
    magazineCapacity: 30,
    muzzleVelocity: 'About 3,100 ft/s',
    origin: 'United States',
    manufacturer: 'Armalite pattern / many manufacturers',
    year: 1963,
    specs: {
      type: 'Semi-automatic rifle',
      action: 'Direct impingement or piston, rotating bolt',
      safeties: 'Manual selector safety',
      sight: 'Iron sights or optical rail',
    },
    color: 'from-amber-700 to-stone-500',
  },
  {
    id: 'm16a4',
    name: 'M16A4',
    category: 'rifle',
    description: 'Fourth-generation U.S. service rifle with a full-length barrel and flat-top upper.',
    caliber: '5.56x45mm NATO',
    barrelLength: '20 in',
    weight: '8.8 lbs',
    magazineCapacity: 30,
    muzzleVelocity: 'About 3,100 ft/s',
    origin: 'United States',
    manufacturer: 'Colt / U.S. military contractors',
    year: 1998,
    specs: {
      type: 'Semi-automatic rifle',
      action: 'Gas-operated, rotating bolt',
      safeties: 'Manual selector safety',
      sight: 'Picatinny rail and detachable carry handle',
    },
    color: 'from-stone-700 to-zinc-500',
  },
  {
    id: 'ak-47',
    name: 'AK-47',
    category: 'rifle',
    description: 'Iconic rifle design known for ruggedness and global influence.',
    caliber: '7.62x39mm',
    barrelLength: '16.3 in',
    weight: '9.5 lbs',
    magazineCapacity: 30,
    muzzleVelocity: 'About 2,350 ft/s',
    origin: 'Soviet Union',
    manufacturer: 'Kalashnikov Concern',
    year: 1947,
    specs: {
      type: 'Rifle',
      action: 'Gas-operated, long-stroke piston',
      safeties: 'Manual lever safety',
      sight: 'Front post and notch rear sight',
    },
    color: 'from-amber-800 to-orange-600',
  },
  {
    id: 'fn-scar-l',
    name: 'FN SCAR-L',
    category: 'rifle',
    description: 'Light variant of the SCAR family built around modularity and controllability.',
    caliber: '5.56x45mm NATO',
    barrelLength: '16.25 in',
    weight: '7.25 lbs',
    magazineCapacity: 30,
    muzzleVelocity: 'About 3,050 ft/s',
    origin: 'Belgium',
    manufacturer: 'FN Herstal',
    year: 2009,
    specs: {
      type: 'Semi-automatic rifle',
      action: 'Gas-operated, short-stroke piston',
      safeties: 'Ambidextrous selector safety',
      sight: 'Picatinny rail system',
    },
    color: 'from-stone-700 to-slate-500',
  },
  {
    id: 'fn-scar-h',
    name: 'FN SCAR-H',
    category: 'rifle',
    description: '7.62 NATO variant of the SCAR platform designed for reach and flexibility.',
    caliber: '7.62x51mm NATO',
    barrelLength: '16.25 in',
    weight: '8.0 lbs',
    magazineCapacity: 20,
    muzzleVelocity: 'About 2,620 ft/s',
    origin: 'Belgium',
    manufacturer: 'FN Herstal',
    year: 2009,
    specs: {
      type: 'Semi-automatic rifle',
      action: 'Gas-operated, short-stroke piston',
      safeties: 'Ambidextrous selector safety',
      sight: 'Picatinny rail system',
    },
    color: 'from-zinc-700 to-stone-500',
  },
  {
    id: 'steyr-aug',
    name: 'Steyr AUG',
    category: 'rifle',
    description: 'Bullpup rifle recognized for its compact layout and integrated optics.',
    caliber: '5.56x45mm NATO',
    barrelLength: '20 in',
    weight: '7.9 lbs',
    magazineCapacity: 30,
    muzzleVelocity: 'About 3,100 ft/s',
    origin: 'Austria',
    manufacturer: 'Steyr Arms',
    year: 1978,
    specs: {
      type: 'Bullpup rifle',
      action: 'Gas-operated, rotating bolt',
      safeties: 'Cross-bolt safety',
      sight: 'Integrated optic on classic variants',
    },
    color: 'from-emerald-700 to-stone-500',
  },
  {
    id: 'hk-g36',
    name: 'HK G36',
    category: 'rifle',
    description: 'German modular rifle built around lightweight polymer construction.',
    caliber: '5.56x45mm NATO',
    barrelLength: '18.9 in',
    weight: '7.9 lbs',
    magazineCapacity: 30,
    muzzleVelocity: 'About 3,050 ft/s',
    origin: 'Germany',
    manufacturer: 'Heckler & Koch',
    year: 1997,
    specs: {
      type: 'Semi-automatic rifle',
      action: 'Gas-operated, rotating bolt',
      safeties: 'Ambidextrous selector safety',
      sight: 'Integrated carry-handle optic or rail',
    },
    color: 'from-stone-700 to-zinc-500',
  },
  {
    id: 'iwi-tavor-x95',
    name: 'IWI Tavor X95',
    category: 'rifle',
    description: 'Compact bullpup rifle developed for modern infantry and close-quarters roles.',
    caliber: '5.56x45mm NATO',
    barrelLength: '16.5 in',
    weight: '7.9 lbs',
    magazineCapacity: 30,
    muzzleVelocity: 'About 3,100 ft/s',
    origin: 'Israel',
    manufacturer: 'Israel Weapon Industries',
    year: 2009,
    specs: {
      type: 'Bullpup rifle',
      action: 'Gas-operated, rotating bolt',
      safeties: 'Ambidextrous selector safety',
      sight: 'Rail-mounted sights or optics',
    },
    color: 'from-amber-700 to-stone-500',
  },
  {
    id: 'fn-fal',
    name: 'FN FAL',
    category: 'rifle',
    description: 'Cold War battle rifle often described as the right arm of the free world.',
    caliber: '7.62x51mm NATO',
    barrelLength: '21 in',
    weight: '9.5 lbs',
    magazineCapacity: 20,
    muzzleVelocity: 'About 2,750 ft/s',
    origin: 'Belgium',
    manufacturer: 'FN Herstal',
    year: 1953,
    specs: {
      type: 'Battle rifle',
      action: 'Gas-operated, tilting bolt',
      safeties: 'Manual lever safety',
      sight: 'Iron sights with adjustable rear',
    },
    color: 'from-stone-700 to-zinc-500',
  },
  {
    id: 'galil-ace',
    name: 'Galil ACE',
    category: 'rifle',
    description: 'Modernized Kalashnikov-derived rifle with refined ergonomics and modular rails.',
    caliber: '5.56x45mm NATO',
    barrelLength: '16.1 in',
    weight: '8.3 lbs',
    magazineCapacity: 30,
    muzzleVelocity: 'About 3,100 ft/s',
    origin: 'Israel',
    manufacturer: 'Israel Weapon Industries',
    year: 2008,
    specs: {
      type: 'Semi-automatic rifle',
      action: 'Gas-operated, long-stroke piston',
      safeties: 'Ambidextrous selector safety',
      sight: 'Rail-mounted sights or optics',
    },
    color: 'from-emerald-700 to-stone-500',
  },
  {
    id: 'mossberg-500',
    name: 'Mossberg 500',
    category: 'shotgun',
    description: 'One of the most common pump-action shotguns in civilian and duty use.',
    caliber: '12 gauge',
    barrelLength: '18.5 in',
    weight: '7.5 lbs',
    magazineCapacity: 5,
    muzzleVelocity: 'About 1,200 ft/s',
    origin: 'United States',
    manufacturer: 'O.F. Mossberg & Sons',
    year: 1961,
    specs: {
      type: 'Pump-action shotgun',
      action: 'Manual pump, slide-action',
      safeties: 'Tang safety',
      sight: 'Bead front sight',
    },
    color: 'from-emerald-700 to-stone-500',
  },
  {
    id: 'remington-870',
    name: 'Remington 870',
    category: 'shotgun',
    description: 'Classic pump shotgun with an enormous installed base and many variants.',
    caliber: '12 gauge',
    barrelLength: '18.5 in',
    weight: '7.0 lbs',
    magazineCapacity: 4,
    muzzleVelocity: 'About 1,200 ft/s',
    origin: 'United States',
    manufacturer: 'Remington Arms',
    year: 1950,
    specs: {
      type: 'Pump-action shotgun',
      action: 'Manual pump, slide-action',
      safeties: 'Cross-bolt safety',
      sight: 'Bead or rifle sights',
    },
    color: 'from-stone-700 to-zinc-500',
  },
  {
    id: 'benelli-m4',
    name: 'Benelli M4',
    category: 'shotgun',
    description: 'Military semi-automatic shotgun using the ARGO gas system.',
    caliber: '12 gauge',
    barrelLength: '18.5 in',
    weight: '8.4 lbs',
    magazineCapacity: 7,
    muzzleVelocity: 'About 1,300 ft/s',
    origin: 'Italy',
    manufacturer: 'Benelli Armi',
    year: 1998,
    specs: {
      type: 'Semi-automatic shotgun',
      action: 'Gas-operated, ARGO system',
      safeties: 'Cross-bolt safety',
      sight: 'Ghost ring sights or rail',
    },
    color: 'from-amber-700 to-stone-500',
  },
  {
    id: 'beretta-1301-tactical',
    name: 'Beretta 1301 Tactical',
    category: 'shotgun',
    description: 'Fast-cycling semi-automatic shotgun tuned for defense and competition.',
    caliber: '12 gauge',
    barrelLength: '18.5 in',
    weight: '6.4 lbs',
    magazineCapacity: 7,
    muzzleVelocity: 'About 1,300 ft/s',
    origin: 'Italy',
    manufacturer: 'Beretta',
    year: 2012,
    specs: {
      type: 'Semi-automatic shotgun',
      action: 'Gas-operated',
      safeties: 'Cross-bolt safety',
      sight: 'Ghost ring sights or optic rail',
    },
    color: 'from-slate-700 to-stone-500',
  },
  {
    id: 'winchester-model-12',
    name: 'Winchester Model 12',
    category: 'shotgun',
    description: 'Historic pump shotgun admired for smooth action and long service life.',
    caliber: '12 gauge',
    barrelLength: '30 in',
    weight: '8.0 lbs',
    magazineCapacity: 5,
    muzzleVelocity: 'About 1,200 ft/s',
    origin: 'United States',
    manufacturer: 'Winchester Repeating Arms',
    year: 1912,
    specs: {
      type: 'Pump-action shotgun',
      action: 'Manual pump, slide-action',
      safeties: 'Manual safety',
      sight: 'Bead front sight',
    },
    color: 'from-stone-700 to-zinc-500',
  },
  {
    id: 'ithaca-37',
    name: 'Ithaca 37',
    category: 'shotgun',
    description: 'Bottom-ejecting pump shotgun derived from the Browning patents era.',
    caliber: '12 gauge',
    barrelLength: '18.5 in',
    weight: '6.6 lbs',
    magazineCapacity: 5,
    muzzleVelocity: 'About 1,200 ft/s',
    origin: 'United States',
    manufacturer: 'Ithaca Gun Company',
    year: 1937,
    specs: {
      type: 'Pump-action shotgun',
      action: 'Manual pump, slide-action',
      safeties: 'Cross-bolt safety',
      sight: 'Bead front sight',
    },
    color: 'from-emerald-700 to-stone-500',
  },
  {
    id: 'browning-auto-5',
    name: 'Browning Auto-5',
    category: 'shotgun',
    description: 'Landmark recoil-operated semi-automatic shotgun introduced in the early 20th century.',
    caliber: '12 gauge',
    barrelLength: '28 in',
    weight: '8.0 lbs',
    magazineCapacity: 4,
    muzzleVelocity: 'About 1,300 ft/s',
    origin: 'Belgium',
    manufacturer: 'Browning',
    year: 1903,
    specs: {
      type: 'Semi-automatic shotgun',
      action: 'Long recoil operated',
      safeties: 'Manual safety',
      sight: 'Bead front sight',
    },
    color: 'from-amber-800 to-stone-600',
  },
  {
    id: 'spas-12',
    name: 'SPAS-12',
    category: 'shotgun',
    description: 'Famous Italian tactical shotgun with both semi-automatic and pump-action operation.',
    caliber: '12 gauge',
    barrelLength: '21 in',
    weight: '9.9 lbs',
    magazineCapacity: 8,
    muzzleVelocity: 'About 1,200 ft/s',
    origin: 'Italy',
    manufacturer: 'Franchi',
    year: 1979,
    specs: {
      type: 'Dual-mode shotgun',
      action: 'Gas-operated semi-auto or pump',
      safeties: 'Cross-bolt safety',
      sight: 'Bead front sight',
    },
    color: 'from-zinc-700 to-stone-500',
  },
  {
    id: 'saiga-12',
    name: 'Saiga-12',
    category: 'shotgun',
    description: 'AK-pattern semi-automatic shotgun built for rugged field use.',
    caliber: '12 gauge',
    barrelLength: '19 in',
    weight: '8.5 lbs',
    magazineCapacity: 5,
    muzzleVelocity: 'About 1,200 ft/s',
    origin: 'Russia',
    manufacturer: 'Izhmash',
    year: 1997,
    specs: {
      type: 'Semi-automatic shotgun',
      action: 'Gas-operated, rotating bolt',
      safeties: 'Manual lever safety',
      sight: 'Iron sights or rail',
    },
    color: 'from-slate-700 to-zinc-500',
  },
  {
    id: 'kel-tec-ksg',
    name: 'Kel-Tec KSG',
    category: 'shotgun',
    description: 'Bullpup pump shotgun with dual tube magazines and compact overall length.',
    caliber: '12 gauge',
    barrelLength: '18.5 in',
    weight: '6.9 lbs',
    magazineCapacity: 14,
    muzzleVelocity: 'About 1,200 ft/s',
    origin: 'United States',
    manufacturer: 'Kel-Tec CNC Industries',
    year: 2011,
    specs: {
      type: 'Pump-action bullpup shotgun',
      action: 'Manual pump, slide-action',
      safeties: 'Cross-bolt safety',
      sight: 'Bead front sight',
    },
    color: 'from-amber-700 to-stone-500',
  },
  {
    id: 'remington-700',
    name: 'Remington 700',
    category: 'sniper',
    description: 'Bolted action platform that became one of the most common precision rifle bases.',
    caliber: '.308 Winchester',
    barrelLength: '24 in',
    weight: '7.5 lbs',
    magazineCapacity: 4,
    muzzleVelocity: 'About 2,800 ft/s',
    origin: 'United States',
    manufacturer: 'Remington Arms',
    year: 1962,
    specs: {
      type: 'Bolt-action rifle',
      action: 'Manually operated bolt',
      safeties: 'Two-position safety',
      sight: 'Scope rail and iron sight options',
    },
    color: 'from-indigo-700 to-zinc-500',
  },
  {
    id: 'm40a5',
    name: 'M40A5',
    category: 'sniper',
    description: 'Marine Corps precision rifle built on the Remington 700 pattern.',
    caliber: '.308 Winchester',
    barrelLength: '25 in',
    weight: '9.0 lbs',
    magazineCapacity: 5,
    muzzleVelocity: 'About 2,700 ft/s',
    origin: 'United States',
    manufacturer: 'Remington / U.S. Marine Corps armory',
    year: 2009,
    specs: {
      type: 'Bolt-action precision rifle',
      action: 'Manually operated bolt',
      safeties: 'Two-position safety',
      sight: 'Optics rail with precision scope',
    },
    color: 'from-slate-700 to-indigo-500',
  },
  {
    id: 'accuracy-international-awm',
    name: 'Accuracy International AWM',
    category: 'sniper',
    description: 'Long-range rifle known for its use in .338 Lapua Magnum chamberings.',
    caliber: '.338 Lapua Magnum',
    barrelLength: '27 in',
    weight: '14.6 lbs',
    magazineCapacity: 5,
    muzzleVelocity: 'About 2,950 ft/s',
    origin: 'United Kingdom',
    manufacturer: 'Accuracy International',
    year: 1996,
    specs: {
      type: 'Bolt-action precision rifle',
      action: 'Manually operated bolt',
      safeties: 'Two-position safety',
      sight: 'Precision optic rail',
    },
    color: 'from-indigo-700 to-stone-500',
  },
  {
    id: 'barrett-m82a1',
    name: 'Barrett M82A1',
    category: 'sniper',
    description: 'Semi-automatic .50 caliber rifle used as an anti-materiel platform.',
    caliber: '.50 BMG',
    barrelLength: '29 in',
    weight: '32.7 lbs',
    magazineCapacity: 10,
    muzzleVelocity: 'About 2,800 ft/s',
    origin: 'United States',
    manufacturer: 'Barrett Firearms Manufacturing',
    year: 1982,
    specs: {
      type: 'Semi-automatic anti-materiel rifle',
      action: 'Recoil-operated, rotating bolt',
      safeties: 'Manual safety',
      sight: 'Optic rail',
    },
    color: 'from-stone-700 to-zinc-500',
  },
  {
    id: 'mcmillan-tac-50',
    name: 'McMillan TAC-50',
    category: 'sniper',
    description: 'Extreme-range precision rifle chambered for .50 BMG.',
    caliber: '.50 BMG',
    barrelLength: '29 in',
    weight: '26.0 lbs',
    magazineCapacity: 5,
    muzzleVelocity: 'About 2,800 ft/s',
    origin: 'United States',
    manufacturer: 'McMillan Firearms',
    year: 2000,
    specs: {
      type: 'Bolt-action precision rifle',
      action: 'Manually operated bolt',
      safeties: 'Two-position safety',
      sight: 'Precision optic rail',
    },
    color: 'from-slate-700 to-indigo-500',
  },
  {
    id: 'sako-trg-42',
    name: 'Sako TRG 42',
    category: 'sniper',
    description: 'Finnish precision rifle favored for long-range accuracy and repeatability.',
    caliber: '.338 Lapua Magnum',
    barrelLength: '27 in',
    weight: '13.2 lbs',
    magazineCapacity: 10,
    muzzleVelocity: 'About 2,950 ft/s',
    origin: 'Finland',
    manufacturer: 'Sako',
    year: 1999,
    specs: {
      type: 'Bolt-action precision rifle',
      action: 'Manually operated bolt',
      safeties: 'Two-position safety',
      sight: 'Precision optic rail',
    },
    color: 'from-indigo-700 to-stone-500',
  },
  {
    id: 'cheytac-m200',
    name: 'CheyTac M200 Intervention',
    category: 'sniper',
    description: 'Long-range rifle designed around the .408 CheyTac cartridge.',
    caliber: '.408 CheyTac',
    barrelLength: '29 in',
    weight: '27.0 lbs',
    magazineCapacity: 7,
    muzzleVelocity: 'About 3,000 ft/s',
    origin: 'United States',
    manufacturer: 'CheyTac USA',
    year: 2001,
    specs: {
      type: 'Bolt-action precision rifle',
      action: 'Manually operated bolt',
      safeties: 'Two-position safety',
      sight: 'Precision optic rail',
    },
    color: 'from-slate-700 to-indigo-500',
  },
  {
    id: 'barrett-mrad',
    name: 'Barrett MRAD',
    category: 'sniper',
    description: 'Modular precision rifle adopted for military precision shooting requirements.',
    caliber: '.338 Lapua Magnum',
    barrelLength: '27 in',
    weight: '13.9 lbs',
    magazineCapacity: 10,
    muzzleVelocity: 'About 2,950 ft/s',
    origin: 'United States',
    manufacturer: 'Barrett Firearms Manufacturing',
    year: 2010,
    specs: {
      type: 'Bolt-action precision rifle',
      action: 'Manually operated bolt',
      safeties: 'Two-position safety',
      sight: 'Precision optic rail',
    },
    color: 'from-indigo-700 to-zinc-500',
  },
  {
    id: 'ruger-precision-rifle',
    name: 'Ruger Precision Rifle',
    category: 'sniper',
    description: 'Affordable modular precision rifle that brought long-range shooting to a wider audience.',
    caliber: '.308 Winchester',
    barrelLength: '24 in',
    weight: '10.7 lbs',
    magazineCapacity: 10,
    muzzleVelocity: 'About 2,820 ft/s',
    origin: 'United States',
    manufacturer: 'Sturm, Ruger & Co.',
    year: 2015,
    specs: {
      type: 'Bolt-action precision rifle',
      action: 'Manually operated bolt',
      safeties: 'Manual safety',
      sight: 'Optic rail',
    },
    color: 'from-slate-700 to-stone-500',
  },
  {
    id: 'm24-sws',
    name: 'M24 Sniper Weapon System',
    category: 'sniper',
    description: 'Standard U.S. Army precision rifle based on the Remington 700 action.',
    caliber: '.308 Winchester',
    barrelLength: '24 in',
    weight: '14.3 lbs',
    magazineCapacity: 5,
    muzzleVelocity: 'About 2,780 ft/s',
    origin: 'United States',
    manufacturer: 'Remington Arms / U.S. Army',
    year: 1988,
    specs: {
      type: 'Bolt-action precision rifle',
      action: 'Manually operated bolt',
      safeties: 'Two-position safety',
      sight: 'Precision optic rail',
    },
    color: 'from-indigo-700 to-zinc-500',
  },
  {
    id: 'm249-saw',
    name: 'M249 SAW',
    category: 'machine',
    description: 'Squad automatic weapon built for sustained suppressive fire.',
    caliber: '5.56x45mm NATO',
    barrelLength: '18.3 in',
    weight: '17.0 lbs',
    magazineCapacity: 200,
    muzzleVelocity: 'About 3,050 ft/s',
    origin: 'United States',
    manufacturer: 'FN Manufacturing',
    year: 1984,
    specs: {
      type: 'Light machine gun',
      action: 'Gas-operated, open bolt',
      safeties: 'Manual safety',
      sight: 'Iron sights or optic rail',
    },
    color: 'from-rose-700 to-orange-500',
  },
  {
    id: 'm240b',
    name: 'M240B',
    category: 'machine',
    description: 'General-purpose machine gun used widely by U.S. forces.',
    caliber: '7.62x51mm NATO',
    barrelLength: '24.8 in',
    weight: '27.6 lbs',
    magazineCapacity: 100,
    muzzleVelocity: 'About 2,800 ft/s',
    origin: 'Belgium',
    manufacturer: 'FN Herstal',
    year: 1977,
    specs: {
      type: 'General-purpose machine gun',
      action: 'Gas-operated, open bolt',
      safeties: 'Manual safety',
      sight: 'Iron sights or optic rail',
    },
    color: 'from-stone-700 to-orange-500',
  },
  {
    id: 'm60',
    name: 'M60',
    category: 'machine',
    description: 'Historic belt-fed machine gun used by U.S. and allied forces.',
    caliber: '7.62x51mm NATO',
    barrelLength: '22 in',
    weight: '23.3 lbs',
    magazineCapacity: 100,
    muzzleVelocity: 'About 2,800 ft/s',
    origin: 'United States',
    manufacturer: 'Saco Defense',
    year: 1957,
    specs: {
      type: 'General-purpose machine gun',
      action: 'Gas-operated, open bolt',
      safeties: 'Manual safety',
      sight: 'Iron sights',
    },
    color: 'from-amber-800 to-orange-600',
  },
  {
    id: 'mg42',
    name: 'MG42',
    category: 'machine',
    description: 'Highly influential German machine gun known for its high cyclic rate.',
    caliber: '7.92x57mm Mauser',
    barrelLength: '23.6 in',
    weight: '25.3 lbs',
    magazineCapacity: 50,
    muzzleVelocity: 'About 2,500 ft/s',
    origin: 'Germany',
    manufacturer: 'Grofuss / wartime manufacturers',
    year: 1942,
    specs: {
      type: 'General-purpose machine gun',
      action: 'Recoil-operated, open bolt',
      safeties: 'Manual safety',
      sight: 'Iron sights',
    },
    color: 'from-zinc-700 to-orange-500',
  },
  {
    id: 'pkm',
    name: 'PKM',
    category: 'machine',
    description: 'Modernized Soviet-era machine gun recognized for reliability and portability.',
    caliber: '7.62x54mmR',
    barrelLength: '25.3 in',
    weight: '16.5 lbs',
    magazineCapacity: 100,
    muzzleVelocity: 'About 2,800 ft/s',
    origin: 'Soviet Union',
    manufacturer: 'Kalashnikov Concern',
    year: 1961,
    specs: {
      type: 'General-purpose machine gun',
      action: 'Gas-operated, open bolt',
      safeties: 'Manual safety',
      sight: 'Iron sights',
    },
    color: 'from-rose-700 to-stone-500',
  },
  {
    id: 'rpk-74',
    name: 'RPK-74',
    category: 'machine',
    description: 'Light machine gun version of the AK-74 rifle family.',
    caliber: '5.45x39mm',
    barrelLength: '16.3 in',
    weight: '10.8 lbs',
    magazineCapacity: 45,
    muzzleVelocity: 'About 2,900 ft/s',
    origin: 'Soviet Union',
    manufacturer: 'Kalashnikov Concern',
    year: 1974,
    specs: {
      type: 'Light machine gun',
      action: 'Gas-operated, open bolt',
      safeties: 'Manual lever safety',
      sight: 'Iron sights',
    },
    color: 'from-amber-800 to-orange-600',
  },
  {
    id: 'hk-mp5',
    name: 'HK MP5',
    category: 'machine',
    description: 'Classic submachine gun that became a benchmark for compact automatic arms.',
    caliber: '9x19mm Parabellum',
    barrelLength: '8.9 in',
    weight: '5.9 lbs',
    magazineCapacity: 30,
    muzzleVelocity: 'About 1,150 ft/s',
    origin: 'Germany',
    manufacturer: 'Heckler & Koch',
    year: 1966,
    specs: {
      type: 'Submachine gun',
      action: 'Roller-delayed blowback',
      safeties: 'Ambidextrous selector safety',
      sight: 'Iron sights or rail',
    },
    color: 'from-slate-700 to-orange-500',
  },
  {
    id: 'uzi',
    name: 'Uzi',
    category: 'machine',
    description: 'Compact submachine gun used widely by military, police, and security forces.',
    caliber: '9x19mm Parabellum',
    barrelLength: '10 in',
    weight: '7.7 lbs',
    magazineCapacity: 32,
    muzzleVelocity: 'About 1,250 ft/s',
    origin: 'Israel',
    manufacturer: 'Israel Military Industries',
    year: 1954,
    specs: {
      type: 'Submachine gun',
      action: 'Blowback, open bolt',
      safeties: 'Grip safety and manual safety',
      sight: 'Iron sights',
    },
    color: 'from-emerald-700 to-orange-500',
  },
  {
    id: 'fn-p90',
    name: 'FN P90',
    category: 'machine',
    description: 'Personal defense weapon with a distinctive top-mounted magazine.',
    caliber: '5.7x28mm',
    barrelLength: '10.4 in',
    weight: '5.7 lbs',
    magazineCapacity: 50,
    muzzleVelocity: 'About 2,350 ft/s',
    origin: 'Belgium',
    manufacturer: 'FN Herstal',
    year: 1990,
    specs: {
      type: 'Personal defense weapon',
      action: 'Straight blowback, closed bolt',
      safeties: 'Ambidextrous safety',
      sight: 'Integrated reflex or rail-mounted optic',
    },
    color: 'from-slate-700 to-stone-500',
  },
  {
    id: 'thompson-m1a1',
    name: 'Thompson M1A1',
    category: 'machine',
    description: 'World War II era submachine gun famous for its heavy build and .45 caliber power.',
    caliber: '.45 ACP',
    barrelLength: '10.5 in',
    weight: '10.8 lbs',
    magazineCapacity: 30,
    muzzleVelocity: 'About 920 ft/s',
    origin: 'United States',
    manufacturer: 'Auto-Ordnance',
    year: 1942,
    specs: {
      type: 'Submachine gun',
      action: 'Blowback, open bolt',
      safeties: 'Manual safety',
      sight: 'Iron sights',
    },
    color: 'from-amber-800 to-stone-600',
  },
  {
    id: 'ppsh-41',
    name: 'PPSh-41',
    category: 'machine',
    description: 'Mass-produced Soviet submachine gun known for its drum magazine and wartime role.',
    caliber: '7.62x25mm Tokarev',
    barrelLength: '10.6 in',
    weight: '8.8 lbs',
    magazineCapacity: 71,
    muzzleVelocity: 'About 1,600 ft/s',
    origin: 'Soviet Union',
    manufacturer: 'Shpagin',
    year: 1941,
    specs: {
      type: 'Submachine gun',
      action: 'Blowback, open bolt',
      safeties: 'Manual safety',
      sight: 'Iron sights',
    },
    color: 'from-rose-700 to-orange-500',
  },
  {
    id: 'colt-python',
    name: 'Colt Python',
    category: 'revolver',
    description: 'Premium .357 Magnum revolver admired for fit, finish, and smooth operation.',
    caliber: '.357 Magnum',
    barrelLength: '4 in',
    weight: '44 oz',
    magazineCapacity: 6,
    muzzleVelocity: 'About 1,450 ft/s',
    origin: 'United States',
    manufacturer: 'Colt',
    year: 1955,
    specs: {
      type: 'Double-action revolver',
      action: 'Manual cylinder rotation, DA/SA trigger',
      safeties: 'Transfer bar safety',
      sight: 'Adjustable rear sight',
    },
    color: 'from-zinc-700 to-stone-500',
  },
  {
    id: 'smith-wesson-model-29',
    name: 'Smith & Wesson Model 29',
    category: 'revolver',
    description: 'Legendary .44 Magnum revolver made famous by both hunting and cinema.',
    caliber: '.44 Magnum',
    barrelLength: '6.5 in',
    weight: '48 oz',
    magazineCapacity: 6,
    muzzleVelocity: 'About 1,450 ft/s',
    origin: 'United States',
    manufacturer: 'Smith & Wesson',
    year: 1955,
    specs: {
      type: 'Double-action revolver',
      action: 'Manual cylinder rotation, DA/SA trigger',
      safeties: 'Transfer bar safety',
      sight: 'Adjustable rear sight',
    },
    color: 'from-amber-800 to-stone-600',
  },
  {
    id: 'smith-wesson-686',
    name: 'Smith & Wesson 686',
    category: 'revolver',
    description: 'Stainless steel .357 Magnum revolver built for durability and versatility.',
    caliber: '.357 Magnum',
    barrelLength: '4 in',
    weight: '39 oz',
    magazineCapacity: 6,
    muzzleVelocity: 'About 1,250 ft/s',
    origin: 'United States',
    manufacturer: 'Smith & Wesson',
    year: 1980,
    specs: {
      type: 'Double-action revolver',
      action: 'Manual cylinder rotation, DA/SA trigger',
      safeties: 'Transfer bar safety',
      sight: 'Adjustable rear sight',
    },
    color: 'from-stone-700 to-zinc-500',
  },
  {
    id: 'ruger-gp100',
    name: 'Ruger GP100',
    category: 'revolver',
    description: 'Robust medium-frame revolver known for strength and long-term reliability.',
    caliber: '.357 Magnum',
    barrelLength: '4.2 in',
    weight: '40 oz',
    magazineCapacity: 6,
    muzzleVelocity: 'About 1,250 ft/s',
    origin: 'United States',
    manufacturer: 'Sturm, Ruger & Co.',
    year: 1985,
    specs: {
      type: 'Double-action revolver',
      action: 'Manual cylinder rotation, DA/SA trigger',
      safeties: 'Transfer bar safety',
      sight: 'Adjustable rear sight',
    },
    color: 'from-slate-700 to-stone-500',
  },
  {
    id: 'colt-single-action-army',
    name: 'Colt Single Action Army',
    category: 'revolver',
    description: 'Historic single-action revolver that became an icon of the American West.',
    caliber: '.45 Colt',
    barrelLength: '5.5 in',
    weight: '40 oz',
    magazineCapacity: 6,
    muzzleVelocity: 'About 850 ft/s',
    origin: 'United States',
    manufacturer: 'Colt',
    year: 1873,
    specs: {
      type: 'Single-action revolver',
      action: 'Manually cocked hammer and rotating cylinder',
      safeties: 'Half-cock notch',
      sight: 'Fixed notch and blade sight',
    },
    color: 'from-amber-800 to-stone-600',
  },
  {
    id: 'webley-mk-vi',
    name: 'Webley Mk VI',
    category: 'revolver',
    description: 'British service revolver with a top-break frame and military pedigree.',
    caliber: '.455 Webley',
    barrelLength: '6 in',
    weight: '42 oz',
    magazineCapacity: 6,
    muzzleVelocity: 'About 700 ft/s',
    origin: 'United Kingdom',
    manufacturer: 'Webley & Scott',
    year: 1915,
    specs: {
      type: 'Double-action revolver',
      action: 'Top-break, DA/SA trigger',
      safeties: 'Hammer safety notch',
      sight: 'Fixed front blade and rear notch',
    },
    color: 'from-zinc-700 to-stone-500',
  },
  {
    id: 'nagant-m1895',
    name: 'Nagant M1895',
    category: 'revolver',
    description: 'Unusual gas-sealed revolver that served across multiple eras in Eastern Europe.',
    caliber: '7.62x38mmR',
    barrelLength: '4.5 in',
    weight: '28 oz',
    magazineCapacity: 7,
    muzzleVelocity: 'About 750 ft/s',
    origin: 'Belgium / Russian Empire',
    manufacturer: 'Nagant',
    year: 1895,
    specs: {
      type: 'Double-action revolver',
      action: 'Manual cylinder rotation, DA/SA trigger',
      safeties: 'Hammer safety notch',
      sight: 'Fixed iron sights',
    },
    color: 'from-slate-700 to-zinc-500',
  },
  {
    id: 'taurus-raging-bull',
    name: 'Taurus Raging Bull',
    category: 'revolver',
    description: 'Heavy hunting revolver built for magnum cartridges and recoil management.',
    caliber: '.44 Magnum',
    barrelLength: '6.5 in',
    weight: '53 oz',
    magazineCapacity: 6,
    muzzleVelocity: 'About 1,400 ft/s',
    origin: 'Brazil',
    manufacturer: 'Taurus',
    year: 1997,
    specs: {
      type: 'Double-action revolver',
      action: 'Manual cylinder rotation, DA/SA trigger',
      safeties: 'Transfer bar safety',
      sight: 'Adjustable rear sight',
    },
    color: 'from-rose-700 to-stone-500',
  },
  {
    id: 'ruger-blackhawk',
    name: 'Ruger Blackhawk',
    category: 'revolver',
    description: 'Single-action revolver platform built for powerful hunting loads and durability.',
    caliber: '.357 Magnum',
    barrelLength: '6.5 in',
    weight: '41 oz',
    magazineCapacity: 6,
    muzzleVelocity: 'About 1,250 ft/s',
    origin: 'United States',
    manufacturer: 'Sturm, Ruger & Co.',
    year: 1955,
    specs: {
      type: 'Single-action revolver',
      action: 'Manually cocked hammer and rotating cylinder',
      safeties: 'Transfer bar safety',
      sight: 'Adjustable rear sight',
    },
    color: 'from-stone-700 to-zinc-500',
  },
  {
    id: 'kimber-k6s',
    name: 'Kimber K6s',
    category: 'revolver',
    description: 'Modern compact six-shot revolver designed for concealed carry.',
    caliber: '.357 Magnum',
    barrelLength: '2 in',
    weight: '23 oz',
    magazineCapacity: 6,
    muzzleVelocity: 'About 1,200 ft/s',
    origin: 'United States',
    manufacturer: 'Kimber Manufacturing',
    year: 2016,
    specs: {
      type: 'Double-action revolver',
      action: 'Manual cylinder rotation, DA/SA trigger',
      safeties: 'Internal hammer safety',
      sight: 'Fixed low-profile sights',
    },
    color: 'from-amber-700 to-stone-500',
  },
];

export function buildCategories(collection: Firearm[]): CategorySummary[] {
  return categoryDefinitions.map((definition) => ({
    ...definition,
    count: collection.filter((firearm) => firearm.category === definition.id).length,
  }));
}

export function buildStats(collection: Firearm[]): StatSummary[] {
  const uniqueOrigins = new Set(collection.map((firearm) => firearm.origin)).size;
  const years = collection.map((firearm) => firearm.year);
  const minYear = Math.min(...years);
  const maxYear = Math.max(...years);

  return [
    { label: 'Total Weapons', value: collection.length, icon: 'Zap' },
    { label: 'Categories', value: categoryDefinitions.length, icon: 'Grid' },
    { label: 'Origin Countries', value: uniqueOrigins, icon: 'Globe' },
    { label: 'Time Span', value: `${maxYear - minYear} years`, icon: 'Clock' },
  ];
}

export function getOrigins(collection: Firearm[]): string[] {
  return Array.from(new Set(collection.map((firearm) => firearm.origin))).sort();
}

export function getCalibers(collection: Firearm[]): string[] {
  return Array.from(new Set(collection.map((firearm) => firearm.caliber))).sort();
}

export function getActionTypes(collection: Firearm[]): string[] {
  return Array.from(
    new Set(
      collection.map((firearm) => firearm.specs.type)
    )
  ).sort();
}
